@startuml
skinparam classAttributeIconSize 0

class GetUnladenCenterMassController{
    +getUnLadenCenterOfMassOfShip(mmsi)
}

class Company {}


class Ship {
    +addNewBlockOfContainersToShip(mass, nContainers)
    +getTotalArea()
    +getCenterOfMassX()
    +getCenterOfMassY()
    +getCenterOfMass()
}

class Mass {
    +getX()
    +getY()
}

GetUnladenCenterMassController ..> Company
GetUnladenCenterMassController ..> Ship
GetUnladenCenterMassController ..> Mass
Company "1" -- "1..*" Ship : owns >
Ship "1" -- "1..*" Mass : has >
@enduml