@startuml

skinparam classAttributeIconSize 0
hide empty methods
hide empty attributes

class Company {
    -designation
}

class TrafficManager {}

class Ship {
    -mmmsiCode
    -shipName
    -imoCode
    -callSignId
    -currentCapacity /'added by us'/
    -draft
}

class ShipPosition {
    -baseDateTime
    -latitude
    -longitude
    -sog
    -cog
    -heading
    -position
    -transceiver
}

Ship "1" -- "1..*" ShipPosition : has >
TrafficManager "1" -- "1..*" ShipPosition : controls >
Company "1" -- "1..*" Ship : owns >

@enduml