@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Ship Captain" as SC

activate SC
SC-> ":System" : wants to check the audit trail of a given container of a given cargo manifest
activate ":System"
":System" --> SC : asks for data(cargo manifest id, container id)
SC-> ":System" : inserts needed data
":System" --> SC : returns the audit trail in chronological order

deactivate ":System"

@enduml