@startuml
'https://plantuml.com/class-diagram

/'class Company{

}'/

class Ship{
    **MMSI** [int]
    VesselTypeID [int]
    IMO [string]
    CallSignId [string]
    ShipName [string]
    CurrentCapacity [double]
    Draft[double]
    Length [double]
    Width [double]
    maxCapacity [double]
}
class Continent{
   ** continent_id** [int]
    continent_name [string]
}
class ShipTrip{
    **ship_trip_id** [int]
    FK mmsi [int]
    FK departure_location_id [int]
    FK arrival_location_id [int]
    FK loading_cargo_id [int]
    FK unloading_cargo_id [int]
    est_departure_date [date]
    real_departure_date [date]
    est_arrival_date  [date]
    real_arrival_date  [date]
}
class ShipPosition{
    **BaseDateTime** [Date]
    **Latitude** [double]
    **Longitude** [double]
    IMO FK [String]
    Sog [double]
    Cog [double]
    Heading [double]
    Position [double]
    Transceiver [String] /'perguntar ao grupo'/
}

class Container{
    **ContainerID** [int]
    Payload [int]
    Tare [int]
    Gross [int]
    CheckDigit [int]
    ISOCode [String]
}

class EnergyPower{
    **NumEnergyGenerators** [int]
    **MMSI** FK [int]
    GeneratorsPower [int]
}
/'refrigeration state is ambigous'/

/'manifest type(loading, unloading) changes its values'/
class CargoManifest{
    **CargoManifestID** [int]
    **locationId** FK [int]
    IMO FK [String]
    TypeOfTransport [String]
    Status [String]
}

class PositionInVehicule{
    **CargoManifestID**FK [int]
    **ContainerID**FK [int]
    ContainerPositionInVehiculeX [int]
    ContainerPositionInVehiculeY [int]
    ContainerPositionInVehiculeZ [int]
}

class Port {
    **portId** [int]
    Name [String]
    fk_location_id [int]
}

class Warehouse {
    **warehouseId** [int]
    Name [String]
    fk_location_id [int]

}

class Country{
    **Country** [String]
    Continent [String]
}

class PlaceLocation{
    **location_id** [int]
    locationLatitude [double]
    LocationLongitude [double]
    Country[String]
}

class ContainerInCargoManifest{
    ** ContainerID ** FK PK [int]
    ** CargoManifestId **  FK PK [int]
    temperature_kept [double]
}
class Shipment{
    **shipment_id** [int]
    FK_container_id[int]
    FK_shiptrip_id[int]
}


/'class Truck{
    truckID
}

class Transports{
    truckId FK
    warehouseId FK
}'/




Ship "1" -- "1..*" Container : transports >
Ship "1" -- "1..*" ShipPosition
/'Docking "1" -- "1..2" CargoManifest'/
ShipTrip "1" -- "2" Port

Ship "1" -- "*" ShipTrip
CargoManifest "1" -- "1..*" ContainerInCargoManifest
Container "*" -- "1" ContainerInCargoManifest
/'Truck "1" -- "1..*" CargoManifest'/
/'
Truck "*" -- "1" Container
'/
Port "0..1" -- "1" CargoManifest
Warehouse "0..1" -- "1" CargoManifest
PlaceLocation "*" -- "1" Country
Continent "1" -- "1..*" Country
PlaceLocation "1" -- "1" Port
PlaceLocation "1" -- "1" Warehouse

/'Relacoes N para N, falta relacao'/
/'
Truck "1..*" -- "1..*" Warehouse
'/
/'Ship "1" -- "*" Docking'/
ShipTrip "1" -- "1..2" CargoManifest
Ship "1" -- "*" EnergyPower : has >
ContainerInCargoManifest "1..*" -- "1..*" PositionInVehicule
EnergyPower "1" -- "1..*" ContainerInCargoManifest
Container "1" -- "*" Shipment
Shipment "1..*" -- "1" ShipTrip
@enduml