@startuml

autonumber
actor Client as C

participant "GetContainerSituationUI" as UI
participant "GetContainerSituationController" as CTRL
participant "Company" as COMPANY
participant "App" as APP
participant "databaseConnection:\nDatabaseConnection" as CONNECTION

participant "RouteStoreDB" as ROUTE_STORE_DB

/'Temos de chamar a Company para as Stores ou não é
necessário?'/


activate C
C -> "UI" : asks to obtain the situation of container
activate "UI"
"UI" --> C : requests the registration code
deactivate "UI"
C -> "UI" : types the registration code
activate "UI"
UI --> C : requests the container id
deactivate UI
C -> UI : types the container id
activate UI
UI -> CTRL : getContainerSituation(containerID, registrationCode)
activate CTRL
CTRL -> COMPANY : routeStoreDB = getRouteStoreDB()
activate COMPANY
deactivate COMPANY
CTRL -> APP : databaseConnection = getInstance().getDatabaseConnection()
activate APP
deactivate APP
CTRL -> ROUTE_STORE_DB : routeId = getRouteId(connection, containerID, registrationCode)
activate ROUTE_STORE_DB
deactivate ROUTE_STORE_DB
CTRL -> ROUTE_STORE_DB : containerLocation = getContainerSituation(connection, routeID)
activate ROUTE_STORE_DB
deactivate ROUTE_STORE_DB
CTRL --> UI : containerLocation
deactivate CTRL
UI --> C : displays the type and concrete instance of its current location
deactivate UI
deactivate C

@enduml