@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class AuthFacade{
    +boolean addUserRole(String id, String description)
    +addUser(String name, String email, String pwd)
    +boolean addUserWithRole(String name, String email, String pwd, String roleId)
    /'+boolean addUserWithRoles(String name, String email, String pwd, String[] rolesId)]'/
    +boolean existsUser(String email)
    +UserSession doLogin(String email, String password)
    +UserSession getCurrentUserSession()
    +void doLogout()
}

class UserSession{
    +boolean isLoggedIn()
    +boolean isLoggedInwWithRole(String roleId)
    +String getUserName()
    +Email getUserId()
}



@enduml