@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
left to right direction

class User{
-name
-email
-password
}

class Role{
    -id
    -description
}

User "*" -- "1" Role : plays

@enduml