@startuml
autonumber
actor Client as C

activate C
C -> ":System" : asks to obtain the route of container
activate ":System"
":System" --> C : requests the registration code
deactivate ":System"
C -> ":System" : types the registration code
":System" --> C : requests the container id
deactivate ":System"
C -> ":System" : types the container id
activate ":System"
":System" --> C : displays the route until current location
deactivate ":System"

deactivate C
@enduml